### ISSUE TITLE
Time to document about Msys2

### ISSUE THREAD

**Issue by ghost** [cirosantilli/windows-cheat#1]
I guess nobody else is going to create an issue for this kind of questions... Just a greeting ;)

**Comment by cirosantilli** [comment]
Hi Qian, sorry if I forgot, but have we met?

In any case nice to hear from you.

As you can see my Windows skills are inexistent, and whenever this repo get pushes, it is a moment of (trying to reduce) pain for me :-)

I don't clearly understand the difference between mingw and cygwin, but is msys2 an alternative to them?

In any case, come to the Linux side of the force. If you want POSIX, you need an OS whose syscalls are made to support it >:-)

**Comment by ghost** [comment]
No, we didn't met ;)

I searched for some open source contributor and found all-github-commit-emails, then browsed your repo for curious.

Cygwin re-implements POSIX api on top of Win32 api, for example, posix fork() maps to CreateProcess() and a lot of crazy hack, as a result the performance is bad. The reason to use Cygwin API is, (almost) no source changing is required to re-compile unix tool for Windows.

MinGW does not support POSIX, instead, it re-implements Microsoft compatible header files so Win32 program can be compiled by gcc rather than MS VC++.

If a program imports cygwin1.dll, then it was compiled on Cygwin platform, otherwise it should import kernel32.dll/ntdll.dll/msvcrt.dll/etc, and was either compiled by MinGW gcc or VC++ or similar.

Msys2 is a fork of Cygwin, combines with a group of MinGW tool chains and libraries, with pacman as builtin package manager. It uses cygwin POSIX api to bootstrap some critical unix tools, and then use those unix tools to assist the complication of MinGW tool chains and libraries, so that cross-platform libraries like libpng/gtk/Qt/Boost can be built with almost same command lines on both Windows and Linux.

Hopes that make things clearer :)

Feel free to close the issue, it's just a greeting.

Have a look a https://www.tea-ci.org if you feel boring and are willing to contribute to Wine+Msys2 ;)

**Comment by cirosantilli** [comment]
I think I understand a bit better now, basically you combine the best of Cygwin (the POSIX API) and mingw (GCC) is that it?

Actually I admire this kind of project, it's just that I'm an idealist and I'd rather have the full open source OS ;-)

Well I'll close this for now, but fell free to ping me here or anywhere else when feel like it ;-)

**Comment by ghost** [comment]
> basically you combine the best of Cygwin (the POSIX API) and mingw (GCC) is that it?

Yes, and package management.

Cool job for the rest. :)
